# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ronald's Blog
tagline:             'Blog by Ronald Bosma'
description:         'Blog by Ronald Bosma'
url:                 https://ronaldbosma.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ronald Bosma
  url:               https://twitter.com/ronaldbosma1
  email:             ronald.bosma@infosupport.com

# Custom vars
version:             1.0.0
